[package]
name = "faf-dns-proxy"
version = "0.6.0"
authors = ["James Bates <errantmind@protonmail.com>"]
edition = "2021"

[profile.dev]
opt-level = 1
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
panic = 'abort'
codegen-units = 1
lto = "thin"
debug = false
incremental = false
overflow-checks = false
strip = 'symbols'

[features]
default = []

[dependencies]
tcmalloc = { version = "~0.3.0", default-features = false, features = ["bundled"] }

clap = { version = "^4.4.10", default-features = true, features = ["derive"] }
lazy_static = "^1.4.0"
once_cell = "^1.18"
webpki-roots = "~0.26.0"
hashbrown = { version = "~0.14.3", default-features = true, features = ["inline-more", "ahash"] }

# faster hasher for keys that are particular primitives
nohash-hasher = "~0.2.0"

# faster channel
kanal = "0.1.0-pre8"

# async runtime/executor
tokio = { version = "^1.34.0", features = ["rt-multi-thread", "net", "io-util", "time", "macros", "sync"] }
tokio-rustls = { version = "~0.24.1", features = ["default", "early-data"] }

