[package]
name = "faf-dns-proxy"
version = "0.5.3"
authors = ["James Bates <errantmind@protonmail.com>"]
edition = "2021"

[profile.dev]
opt-level = 1
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
panic = 'abort'
codegen-units = 1
lto = "thin"
debug = false
incremental = false
overflow-checks = false
strip = 'symbols'

[features]
default = []

[dependencies]
# FFI bindings to better allocator designed by Microsoft
mimalloc = { version = "*", default-features = false }

clap = { version = "*", default-features = true, features = ["derive"] }
lazy_static = "*"
once_cell = "*"
webpki-roots = "*"
hashbrown = { version = "*", default-features = true, features = ["inline-more", "ahash"] }

# faster hasher for keys that are particular primitives
nohash-hasher = "*"

# faster channel
kanal = "0.1.0-pre8"

# async runtime/executor
tokio = { version = "*", features = ["rt-multi-thread", "net", "io-util", "time", "macros", "parking_lot", "sync"] }
tokio-rustls = { version = "*", features = ["default", "early-data"] }

